const categoryArray = [
    "accessories stock data",
    "accessory data",
    "adapters data",
    "conference device data",
    "desktop data",
    "gk-access point-db",
    "gk-cables db",
    "gk-chassis server-db",
    "gk-electric cable stock",
    "gk-firewall-db",
    "gk-io ports & patch panels-db",
    "gk-lan, raid and graphics card-db",
    "gk-liu-db",
    "gk-plotter, xerox, scanner machine-db",
    "gk-processor-db",
    "gk-ram-db",
    "gk-router-db",
    "gk-server-db",
    "gk-sfp-db",
    "gk-storage drive-db",
    "gk-storage-db",
    "gk-switch-db",
    "gk-thin client-db",
    "gk-wlc-db",
    "laptops data",
    "monitor data",
    "phones data",
    "server stock data",
    "switch stock data",
    "tabs data",
    "toner data"
];

module.exports = categoryArray;